file_format: "1"
id: corne
name: Corne
type: shield
url: https://github.com/friction07/corne-xiao 
requires: [seeeduino_xiao_ble]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - studio
siblings:
  - corne_xiao_v1_left
  - corne_xiao_v1_right
